/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/***************** Inclusión de librerías *****************/
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "string.h"
#include "Config.h"
#include "RCC.h"
#include "Delay.h"
#include "GPIO_Config.h"
#include "USART.h"

/*Definiciones*/

//LED
#define PIN_USER_LED	5
#define GPIO_USER_LED	GPIOA

//USER BUTTON
#define PIN_USER_BUTTON		13
#define GPIO_USER_BUTTON	GPIOC

/* Tipos, estructuras y enumeraciones */
typedef enum
{
	WFI = 0,
	WFE
}Wait_For_STH_e;

typedef enum
{
	MODE_SLEEP = 0,
	MODE_STOP,
	MODE_STANDBY
}Sleep_Mode_e;

typedef struct
{
	Sleep_Mode_e mode;
	uint8_t seven_on_pend; //1 = enable seven on pending
	Wait_For_STH_e wait_for_sth;
}Config_Sleep_t;

/* Variables globales */

//tim4
uint32_t uwTick_tim4;

//sleep
Config_Sleep_t config_sleep = {.mode = MODE_STOP, .seven_on_pend = 0, .wait_for_sth = WFI};

//usart2
USARTx_Config_t USART2_Config = { 	.USARTx = USART2,
									.baudrate = 115200,
									.m_bit = M_8BITS,
									.over_bit = OVER_16,
									.enable_parity = PARITY_DIS,
									.stop_bit = STOP_ONE,
									.priority = 1};
volatile uint8_t len = 0;
uint8_t Tx_Data[100] = {0};

//buton exti
EXTI_Config_t exti13 = {.en = 1, .exti_pin = PIN_USER_BUTTON, .trigger = FALLING_IT, .priority = 2};

/* Prototipo de funciones */

void Sleep_On_Exit_Config(Config_Sleep_t *config);
void Sleep_Mode_Config(Config_Sleep_t *config);

void tim4_init(uint32_t ck_psc);
void tim4_delay(uint32_t delay);

/* Función principal */
int main(void)
{

	//Clock Config
	flash_config();
	PLL_Config(HSI_SOURCE);
	#if USE_DELAY_US == 1
		Delay_Init(SystemCoreClock/1000000);
	#else
		//Delay_Init(SystemCoreClock/1000);
	#endif

	//Usart2 Config
	USARTx_Init(&USART2_Config); //priority  solo en USARTx_Init_IT

	//Init Led
	GPIO_Output_Config(GPIO_USER_LED, PIN_USER_LED, PUPDR_NONE, OSPEEDR_MEDIUM, OTYPER_PP);

	//EXTI Config
	GPIO_Input_Config(GPIO_USER_BUTTON, PIN_USER_BUTTON, PULL_NONE, &exti13);
	if(config_sleep.wait_for_sth == WFE)
	{
		NVIC_DisableIRQ(EXTI15_10_IRQn); //Deshabilitamos interrupción
		NVIC_ClearPendingIRQ(EXTI15_10_IRQn); //Limpiamos bandera pending
		EXTI -> PR |= EXTI_PR_PR13; //Limpiamos bandera de evento
	}

	//TIM4 Config delay
	tim4_init(84E+6);

	//Sleep Init

	//Para probar el StandBy se recomiendo utilizar el jumper de corriente de la tarjeta
	//Primero mantenemos conectado el puerto COM
	//Quitamos el Jumper y al reconectarlo se verán los  mensajes normales
	//Luego de presionar NRST, volverá a ejecutarse todo pero con la bandera activa.
	Sleep_Mode_Config(&config_sleep);


	//Limpiar la bandera luego del WFE
	if(config_sleep.wait_for_sth == WFE)
	{
		NVIC_ClearPendingIRQ(EXTI15_10_IRQn); //Limpiamos bandera pending
		EXTI -> PR |= EXTI_PR_PR13; //Limpiamos bandera de evento
	}

	//Al salir del modo Stop Mode, debe configurarse el reloj nuevamente ya que por defecto despierta con el HSI y nada más.
	if(config_sleep.mode == MODE_STOP)
	{
		flash_config();
		PLL_Config(HSI_SOURCE);
	}

	while(1)
	{	
		len = sprintf((char*)Tx_Data, "Loop running\r\n");
		USARTx_Send_Data(USART2, Tx_Data, len);
		GPIO_Write_Toggle(GPIO_USER_LED, PIN_USER_LED);
		tim4_delay(1000);

	}
}

/* Definición de funciones */


/* 
* @brief Helpful function to write in console
*/
int __io_putchar(int ch)
{
	uint8_t c = ch & 0xFF;
	ITM_SendChar(c);
	return ch;
}

/*
* @brief Handle EXTI Line 13 interrupt
*/
void EXTI13_User_Handler(void)
{
	//Si se entra luego de un stop, es mejor volver a configurar el reloj.
	//Para imprimir un mensaje por aquí, se debe tener configurado el reloj correctamente
	flash_config();
	PLL_Config(HSI_SOURCE);
	len = sprintf((char*)Tx_Data, "EXTI13\r\n");
	USARTx_Send_Data(USART2, Tx_Data, len);
	return;
}

void Sleep_On_Exit_Config(Config_Sleep_t *config)
{
	uint8_t size_length = 0;

	size_length = sprintf((char*)Tx_Data, "Init Config Sleep On Exit\r\n");
	USARTx_Send_Data(USART2, Tx_Data, size_length);

	//Turn off AHB1 peripherals
	//.........Write needed code

	//Turn off AHB2 peripherals
	//.........Write needed code

	//Automatic AHB clock in sleep RCC_AHBxLPENR register
	//.........Write needed code

	//Automatic APB clock in sleep RCC_APBxLPENR register
	//.........Write needed code

	//Turn off deep sleep
	SCB->SCR &= ~(1U << SCB_SCR_SLEEPDEEP_Pos);

	//Slep on exit from returning from ISR
	SCB->SCR |= (1U << SCB_SCR_SLEEPONEXIT_Pos);


	if(config->wait_for_sth == WFI)
	{
		size_length = sprintf((char*)Tx_Data, "Enter sleep on exit\r\n");
		USARTx_Send_Data(USART2, Tx_Data, size_length);
		__WFI();
	}
	else if(config->wait_for_sth == WFE)
	{
		//Enable seven on pending
		if(config->seven_on_pend == 1)
		{
			size_length = sprintf((char*)Tx_Data, "Seven on pend on\r\n");
			USARTx_Send_Data(USART2, Tx_Data, size_length);
			SCB->SCR |= (1U << SCB_SCR_SEVONPEND_Pos);

		}
		size_length = sprintf((char*)Tx_Data, "Enter sleep on exit\r\n");
		USARTx_Send_Data(USART2, Tx_Data, size_length);
		//Unable possible peripheral events
		//......... Write needed code
		__SEV();
		__WFE();
		__WFE();
	}

	return;
}

/*
 * @brief Config Sleep Mode
 */

void Sleep_Mode_Config(Config_Sleep_t *config)
{
	uint8_t md = config->mode;
	uint8_t size_length = 0;

	size_length = sprintf((char*)Tx_Data, "Init Config Sleep\r\n");
	USARTx_Send_Data(USART2, Tx_Data, size_length);
	//Enable Power Control register
	RCC -> APB1ENR |= RCC_APB1ENR_PWREN;
	//Power Control register
	PWR->CR = 0;

	//Turn off AHB1 peripherals
	//.........Write needed code

	//Turn off AHB2 peripherals
	//.........Write needed code

	//Automatic AHB clock in sleep RCC_AHBxLPENR register
	//.........Write needed code

	//Automatic APB clock in sleep RCC_APBxLPENR register
	//.........Write needed code

	//Flags
	if(PWR->CSR & PWR_CSR_SBF)
	{
		size_length = sprintf((char*)Tx_Data, "Back from Standby\r\n");
		USARTx_Send_Data(USART2, Tx_Data, size_length);
		PWR->CR |= (1U << PWR_CR_CSBF_Pos); //Clear Standby Flag
	}
	PWR->CR |= (1U << PWR_CR_CWUF_Pos); //Clear Wakeup Flag
	
	//seven on pending, sleepdeep, sleep on exit = turn-off
	SCB->SCR = 0;

	switch (md)
	{
		case MODE_SLEEP:
			size_length = sprintf((char*)Tx_Data, "Config Sleep Mode\r\n");
			USARTx_Send_Data(USART2, Tx_Data, size_length);
			//Enter sleepdeep mode OFF (in programming manual)
			SCB->SCR &= ~(1U << SCB_SCR_SLEEPDEEP_Pos);
			break;
		case MODE_STOP:
			size_length = sprintf((char*)Tx_Data, "Config Stop mode\r\n");
			USARTx_Send_Data(USART2, Tx_Data, size_length);
			//Stop mode ya está activado por defecto
			//Internal regulator
			//PWR->CR |= (1U << PWR_CR_MRLVDS_Pos);
			//Flash power down
			PWR->CR |= (1U << PWR_CR_FPDS_Pos);
			//Enter sleepdeep mode ON(in programming manual)
			SCB->SCR |= (1U << SCB_SCR_SLEEPDEEP_Pos);
			break;
		case MODE_STANDBY:
			size_length = sprintf((char*)Tx_Data, "Config StandBy Mode\r\n");
			USARTx_Send_Data(USART2, Tx_Data, size_length);
			//WakeUp pin enable
			PWR->CSR |= PWR_CSR_EWUP;
			//Standby mode
			PWR->CR |= (1U << PWR_CR_PDDS_Pos);
			//Enter sleepdeep mode ON(in programming manual)
			SCB->SCR |= (1U << SCB_SCR_SLEEPDEEP_Pos);
			break;
		default:
			break;
	}

	if(config->wait_for_sth == WFI)
	{	
		size_length = sprintf((char*)Tx_Data, "Enter sleep mode\r\n");
		USARTx_Send_Data(USART2, Tx_Data, size_length);
		__WFI();
	}
	else if(config->wait_for_sth == WFE)
	{	
		//Enable seven on pending
		if(config->seven_on_pend == 1)
		{	
			size_length = sprintf((char*)Tx_Data, "Seven on pend on\r\n");
			USARTx_Send_Data(USART2, Tx_Data, size_length);
			SCB->SCR |= (1U << SCB_SCR_SEVONPEND_Pos);

		}
		size_length = sprintf((char*)Tx_Data, "Enter sleep mode\r\n");
		USARTx_Send_Data(USART2, Tx_Data, size_length);
		//Unable possible peripheral events
		//......... Write needed code
		__SEV();
		__WFE();
		__WFE();
	}
}

/*
 * @brief Inicialización TIM4 como temporizador no Interrupt
 */

void tim4_init(uint32_t ck_psc)
{
	uint32_t temp;

	/*Activamos RCC del TIM4*/
	RCC->APB1ENR |= RCC_APB1ENR_TIM4EN;
	/*Calculo del prescaler*/
	TIM4->CR1 &= ~TIM_CR1_CEN; //Deshabilitamos
	temp = ck_psc/1000000; //Obtenemos 1us
	TIM4->PSC = temp - 1;
	/*Calculo del auto-reload*/
	TIM4->ARR = 1000 - 1; //Obtenemos 1ms
	//Update
	TIM4->EGR |= (1<<TIM_EGR_UG_Pos);

	/*Activamos conteo*/
	//TIM4->CR1 |= TIM_CR1_CEN;
}

/*
 * @brief Delay utilizando TIM4
 */

void tim4_delay(uint32_t delay)
{
	TIM4->CR1 |= TIM_CR1_CEN; //Activamos conteo
	while(uwTick_tim4 < delay) //uwTick aumentará cada 1ms
	{
		if(TIM4->SR & TIM_SR_UIF)
		{
			TIM4->SR &= ~TIM_SR_UIF;
			uwTick_tim4++;
		}
	}
	uwTick_tim4 = 0;
	TIM4->CR1 &= ~TIM_CR1_CEN; //Desactivamos conteo
	TIM4->CNT = 0;
}

