/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/* Inclución de librerías */
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "RCC.h"
#include "Delay.h"
#include "Config.h"

/* Tipos, estructuras y enumeraciones */

/* Variables globales */
uint32_t systemFreq = 0; // Para revisar la frecuencia actual

/* Prototipo de funciones */


/* Función principal */

int main(void)
{
	flash_config();
	systemFreq = SystemCoreClock;

	while(1)
	{

	}
}

/***************** Definición de funciones *****************/



