/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/***************** Inclusión de librerías *****************/
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "string.h"
#include "Config.h"
#include "RCC.h"
#include "Delay.h"
#include "GPIO_Config.h"
#include "USART.h"
#include "cmsis_os.h"
#include "FreeRTOS.h"
#include "semphr.h"


/*Definiciones*/
#define PIN_LED		5
#define GPIO_LED	GPIOA

#define PIN_BUTTON	13
#define GPIO_BUTTON	GPIOC

#define USE_SWV			0

/* Tipos, estructuras y enumeraciones */
TaskHandle_t led_handle; 	//FreeRTOS
osThreadId button_handle;	//CMSIS OS

/* Variables globales */
EXTI_Config_t ext_var = { .en = 0 };

//usart2
USARTx_Config_t USART2_Config = { 	.USARTx = USART2,
									.baudrate = 115200,
									.m_bit = M_8BITS,
									.over_bit = OVER_8,
									.enable_parity = PARITY_DIS,
									.stop_bit = STOP_ONE,
									.priority = 1};
volatile uint8_t len = 0;
uint8_t Tx_Data[100] = {0};

//global semaphore
SemaphoreHandle_t semButton = NULL;

/* Prototipo de funciones */
void Task_Led(void *params);
void Task_Button(void const *params);


/*CMSIS var*/
osThreadDef(button_name, Task_Button, 2, 0, 1024);

/* Función principal */
int main(void)
{
	BaseType_t status = 0;

	//Usart2 Config
	USARTx_Init(&USART2_Config); //priority  solo en USARTx_Init_IT

	printf("Init Task Creat\r\n");

	//FreeRTOS
	status = xTaskCreate(Task_Led, "Task_Led", 1024, NULL, 2, &led_handle);
	if(status != pdPASS)
	{
		while(1);
	}

	//CMSIS OS
	button_handle = osThreadCreate(osThread(button_name), NULL);
	if(button_handle == NULL)
	{
		while(1);
	}

	//Create Semaph
	semButton = xSemaphoreCreateBinary();

	//Init Scheduler
	osKernelStart(); //CMSIS RTOS
	//vTaskStartScheduler(); //FreeRTOS

	while(1);

}

/* Definición de funciones */

/*
 * @brief
 */

void Task_Led(void *params)
{
	//Config led and initialize
	GPIO_Output_Config(GPIO_LED, PIN_LED, PUPDR_NONE, OSPEEDR_LOW, OTYPER_PP);
	GPIO_Write(GPIO_LED, PIN_LED, 0);
	printf("task led init\r\n");
	while(1)
	{
		//Task is blocking to 2 seconds
		if(xSemaphoreTake(semButton,pdMS_TO_TICKS(2000)))
		{
			GPIO_Write(GPIO_LED, PIN_LED, 1);
			printf("Recibe semaforo\r\n");
		}
		else
		{
			GPIO_Write(GPIO_LED, PIN_LED, 0);
			printf("No se recibe semáforo\r\n");
		}
		vTaskDelay(pdMS_TO_TICKS(1));

	}
}


/*
 * @brief
 */
void Task_Button(void const *params)
{
	//Config button and initialize
	GPIO_Input_Config(GPIO_BUTTON, PIN_BUTTON, PUPDR_NONE, &ext_var);
	printf("task button init\r\n");
	while(1)
	{
		if(GPIO_ReadPin(GPIO_BUTTON, PIN_BUTTON) == 0)
		{
			osDelay(100);
			xSemaphoreGive(semButton);
		}

		osDelay(1);
	}
}

/*******************************/
int __io_putchar(int ch){
#if (USE_SWV== 1)
	ITM_SendChar((uint32_t)ch);
#else
	uint8_t c = ch & 0xFF;
	while(!(USART2->SR & USART_SR_TXE));  //espera hasta que usart este listo para transmitir otro byte
	USART2->DR = c;
#endif
	return ch;
}
