/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/***************** Inclusión de librerías *****************/
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "string.h"
#include "Config.h"
#include "RCC.h"
#include "Delay.h"
#include "GPIO_Config.h"
#include "USART.h"
#include "cmsis_os.h"
#include "FreeRTOS.h"
#include "semphr.h"


/*Definiciones*/
#define PIN_LED_RED		5
#define GPIO_LED_RED	GPIOA
#define PIN_LED_GREEN	6
#define GPIO_LED_GREEN	GPIOA
#define PIN_LED_BLUE	7
#define GPIO_LED_BLUE	GPIOA

#define PIN_BUTTON	13
#define GPIO_BUTTON	GPIOC

#define USE_SWV			0

/* Tipos, estructuras y enumeraciones */

//usart2
USARTx_Config_t USART2_Config = { 	.USARTx = USART2,
									.baudrate = 115200,
									.m_bit = M_8BITS,
									.over_bit = OVER_8,
									.enable_parity = PARITY_DIS,
									.stop_bit = STOP_ONE,
									.priority = 1};

/* Variables globales */
EXTI_Config_t ext_var = { .en = 0 };


volatile uint8_t len = 0;
uint8_t Tx_Data[100] = {0};

//FreeRTOS
TaskHandle_t redTaskHandle;
TaskHandle_t greenTaskHandle;
TaskHandle_t blueTaskHandle;

/* Prototipo de funciones */
void RedTask(void *params);
void GreenTask(void *params);
void BlueTask(void *params);

/* Función principal */
int main(void)
{
	BaseType_t status = 0;

	//Usart2 Config
	USARTx_Init(&USART2_Config); //priority  solo en USARTx_Init_IT

	size_t xFreeStack = xPortGetFreeHeapSize();
	printf("RAM libre antes de crear tarea: %u bytes\r\n", xFreeStack);

	//FreeRTOS
	status = xTaskCreate(RedTask, "red_Led", 256, NULL, 2, &redTaskHandle);
	if(status != pdPASS)
	{
		while(1);
	}

	xFreeStack = xPortGetFreeHeapSize();
	printf("RAM libre antes de crear tarea: %u bytes\r\n", xFreeStack);

	status = xTaskCreate(GreenTask, "green_Led", 256, NULL, 2, &greenTaskHandle);

	if(status != pdPASS)
	{
		while(1);
	}
	xFreeStack = xPortGetFreeHeapSize();
	printf("RAM libre antes de crear tarea: %u bytes\r\n", xFreeStack);

	status = xTaskCreate(BlueTask, "blue_Led", 256, NULL, 2, &blueTaskHandle);

	if(status != pdPASS)
	{
		while(1);
	}

	xFreeStack = xPortGetFreeHeapSize();
	printf("RAM libre antes de crear tarea: %u bytes\r\n", xFreeStack);
	vTaskStartScheduler(); //FreeRTOS

	while(1);

}

/* Definición de funciones */

/*
 * 	@brief RedTask
 */
void RedTask(void *params)
{
	uint8_t first_run = 1;
	GPIO_Output_Config(GPIO_LED_RED, PIN_LED_RED, PUPDR_NONE, OSPEEDR_LOW , OTYPER_PP);
	
	while (1)
	{	
		GPIO_Write(GPIO_LED_RED, PIN_LED_RED, 1);
		vTaskDelay(pdMS_TO_TICKS(500));
		GPIO_Write(GPIO_LED_RED, PIN_LED_RED, 0);	
		vTaskDelay(pdMS_TO_TICKS(500));
		
		if(first_run == 1)
		{
			vTaskDelete(blueTaskHandle);
			first_run = 0;	
		}

	}

}

/*
* 	@brief GreenTask
*/
void GreenTask(void *params)
{
	GPIO_Output_Config(GPIO_LED_GREEN, PIN_LED_GREEN, PUPDR_NONE, OSPEEDR_LOW , OTYPER_PP);

	while(1)
	{
		GPIO_Write(GPIO_LED_GREEN, PIN_LED_GREEN, 1);
		vTaskDelay(pdMS_TO_TICKS(1500));
		vTaskDelete(NULL);
	}
}

/*
* 	@brief BlueTask
*/
void BlueTask(void *params)
{
	GPIO_Output_Config(GPIO_LED_BLUE, PIN_LED_BLUE, PUPDR_NONE, OSPEEDR_LOW , OTYPER_PP);
	
	while (1)
	{
		GPIO_Write_Toggle(GPIO_LED_BLUE, PIN_LED_BLUE);
		vTaskDelay(pdMS_TO_TICKS(200));
	}
	
}


/*******************************/
int __io_putchar(int ch){
#if (USE_SWV== 1)
	ITM_SendChar((uint32_t)ch);
#else
	uint8_t c = ch & 0xFF;
	while(!(USART2->SR & USART_SR_TXE));  //espera hasta que usart este listo para transmitir otro byte
	USART2->DR = c;
#endif
	return ch;
}
