/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/***************** Inclusión de librerías *****************/
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "string.h"
#include "Config.h"
#include "RCC.h"
#include "Delay.h"
#include "GPIO_Config.h"
#include "i2c.h"
#include "eeprom.h"

/*Definiciones*/

//LED
#define PIN_USER_LED	5
#define GPIO_USER_LED	GPIOA

#define EE_ADDR			0x0

/* Tipos, estructuras y enumeraciones */


/* Variables globales */
uint8_t Msg[] = "Hola Mundo Jean Franco";
uint8_t Wr_EEPROM[] = {0x01, 0x04, 0x08, 0xFF, 0xA1};
uint8_t EE_Var1 = 0xCF;
uint8_t EE_Rx_Buff1[5] = {0};


/* Prototipo de funciones */

void I2C_GPIO_Config(void);

/* Función principal */
int main(void)
{

	//Clock Config
	flash_config();
	PLL_Config(HSI_SOURCE);
	#if USE_DELAY_US == 1
		Delay_Init(SystemCoreClock/1000000);
	#else
		Delay_Init(SystemCoreClock/1000);
	#endif

	//LED Config
	GPIO_Output_Config(GPIO_USER_LED, PIN_USER_LED, PUPDR_NONE, OSPEEDR_MEDIUM, OTYPER_PP);

	//I2C Config
	I2C_Config(I2C1);

	delay_ms(500);

	//I2C Send Data
//	EEPROM_Write_N_byte(I2C1, EE_ADDR, 0x0000, Wr_EEPROM, 5);
//	delay_ms(10);
//	EEPROM_Write_N_byte(I2C1, EE_ADDR, 0x0000, &EE_Var1, 1);
//	delay_ms(10);
//	for(uint8_t a = 0; a<=4; a++)
//	{
//		EEPROM_Read_Current_byte(I2C1, EE_ADDR, &EE_Rx_Buff1[a]);
//		delay_ms(10);
//	}

	for(uint8_t a = 1; a<=8; a++)
	{
		EEPROM_Read_N_Bytes(I2C1, EE_ADDR, 0x0000, EE_Rx_Buff1, a);
		delay_ms(10);
	}

	while(1)
	{

		GPIO_Write_Toggle(GPIO_USER_LED, PIN_USER_LED);
		delay_ms(500);
	}
}

/* Definición de funciones */

