/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/* Inclución de librerías */
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "RCC.h"
#include "Delay.h"
#include "DISPLAY_7_SEGM.h"
#include "Config.h"

/*Definiciones*/

#define PRUEBA 0

#define BUTTON1 A, 6
#define BUTTON2 A, 8

#define LED1	A, 7
#define LED2	B, 10
#define LED3	A, 8

/* Tipos, estructuras y enumeraciones */

/* Variables globales */
uint32_t systemFreq = 0; // Para revisar la frecuencia actual

/* Prototipo de funciones */
void Button_Init(void);
void Led_Init(void);

/* Función principal */

int main(void)
{
	flash_config();
	PLL_Config(HSE_SOURCE);
	#if USE_DELAY_US == 1
		Delay_Init(SystemCoreClock/1000000);
	#else
		Delay_Init(SystemCoreClock/1000);
	#endif

	GPIO_CLOCK_ENABLE(A);
	GPIOX_MODER(MODE_OUT,LED);
	GPIOX_PUPDR(MODE_PU_NONE,LED);
	GPIOX_OSPEEDR(MODE_SPD_VHIGH,LED);

#if PRUEBA == 1

	SevenSegment_Init();
	SevenSegment_Clear();

	while(1)
	{
//		for(uint8_t j=1; j<=3; j++)
//		{
//			SevenSegment_SelectDisplay(j);
//
//			for(uint8_t i=0; i<=9; i++)
//			{
//				SevenSegment_DisplayDigit(i);
//				//GPIOX_ODR(LED) = (!(i%2)?1:0);
//				delay_ms(200);
//				SevenSegment_Clear();
//			}
//		}

		for(uint16_t numb_bucle = 0; numb_bucle<=9999; numb_bucle++)
		{
			GPIOX_ODR(LED) = ((numb_bucle%2)?1:0);
			SevenSegment_Integer(numb_bucle, 200);
		}
	}

#else

	Button_Init();
	Led_Init();
	uint8_t i=0;

	while(1)
	{
		i = GPIOX_IDR(BUTTON1);
		while(!(GPIOA -> IDR & (1<<6)))
		{
			i = GPIOX_IDR(BUTTON1);
			GPIOX_ODR(LED1) = 1;
		}

		GPIOX_ODR(LED1) = 0;
	}

#endif

}

/***************** Definición de funciones *****************/

void Button_Init(void)
{
	RCC-> AHB1ENR |= GPIOX_CLOCK(BUTTON1);
	GPIOX_MODER(MODE_DIGITAL_INPUT, BUTTON1);
	GPIOX_PUPDR(MODE_PU_NONE, BUTTON1);

	RCC-> AHB1ENR |= GPIOX_CLOCK(BUTTON2);
	GPIOX_MODER(MODE_DIGITAL_INPUT, BUTTON2);
	GPIOX_PUPDR(MODE_PU_NONE, BUTTON2);
}

void Led_Init(void)
{
	RCC-> AHB1ENR |= GPIOX_CLOCK(LED1);
	GPIOX_MODER(MODE_OUT,LED1);
	GPIOX_PUPDR(MODE_PU_NONE,LED1);
	GPIOX_OSPEEDR(MODE_SPD_VHIGH,LED1);

	RCC-> AHB1ENR |= GPIOX_CLOCK(LED2);
	GPIOX_MODER(MODE_OUT,LED2);
	GPIOX_PUPDR(MODE_PU_NONE,LED2);
	GPIOX_OSPEEDR(MODE_SPD_VHIGH,LED2);
}


