/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/***************** Inclusión de librerías *****************/
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "string.h"
#include "Config.h"
#include "RCC.h"
#include "Delay.h"
#include "GPIO_Config.h"
#include "i2c.h"
#include "math.h"

/*Definiciones*/

//LED
#define PIN_USER_LED	5
#define GPIO_USER_LED	GPIOA

#define EE_ADDR			0x68
#define MPU6050_ADDR	0x68

#define OFFSET_ITERATIONS	100

#define RAD_TO_DEG		57.2957795131f; //180/PI

/* Tipos, estructuras y enumeraciones */


/* Variables globales */
uint8_t Msg[] = "Hola Mundo Jean Franco";
uint8_t Msg1[] = "Hello";
uint8_t Wr_EEPROM[] = {0x01, 0x04, 0x08, 0xFF, 0xA1};
uint8_t EE_Var1 = 0xCF;
uint8_t EE_Rx_Buff1[] = {0};
uint8_t MPU6050_WakeUP[2] = {0x6B, 0x00}; //Dir 6B, Val 00

typedef struct
{
	int16_t Accel_X_offset;
	int16_t Accel_Y_offset;
	int16_t Accel_Z_offset;

	int16_t Accel_X;
	int16_t Accel_Y;
	int16_t Accel_Z;

	float Accel_X_g;
	float Accel_Y_g;
	float Accel_Z_g;

	float roll;
	float pitch;
}MPU6050_Accel_Data_t;

MPU6050_Accel_Data_t Accel;

/* Prototipo de funciones */
void MPU_Read_Accel(MPU6050_Accel_Data_t *Accel_t);
void MPU_Angles(MPU6050_Accel_Data_t *Accel_t);
void MPU_Offset_Calibration(MPU6050_Accel_Data_t *Accel_t);

/* Función principal */
int main(void)
{

	//Clock Config
	flash_config();
	PLL_Config(HSI_SOURCE);
	#if USE_DELAY_US == 1
		Delay_Init(SystemCoreClock/1000000);
	#else
		Delay_Init(SystemCoreClock/1000);
	#endif

	//Init Message
	printf("Configuracion del systick System Clock -> %lu\n",SystemCoreClock);

	//Init Led
	GPIO_Output_Config(GPIO_USER_LED, PIN_USER_LED, PUPDR_NONE, OSPEEDR_MEDIUM, OTYPER_PP);

	//Init I2C
	I2C_Config(I2C1);

	//Comprobate MPU6050
	while(I2C_Master_Read_Register_Bytes(I2C1, 0x68, 0x75, Size_8bits, EE_Rx_Buff1, 1));
	memset(EE_Rx_Buff1,0,sizeof(EE_Rx_Buff1));

	//Wake up MPU6050
	I2C_Master_Send_Data(I2C1, MPU6050_ADDR, MPU6050_WakeUP, sizeof(MPU6050_WakeUP));

	//Comprobate WakeUp MPU6050
	I2C_Master_Read_Register_Bytes(I2C1, MPU6050_ADDR, 0x6B, Size_8bits, EE_Rx_Buff1, 1);

	//Calibración
	MPU_Offset_Calibration(&Accel);

	while(1)
	{	
		MPU_Read_Accel(&Accel);
		//printf("Ax: %.2f , Ay: %.2f, Az: %.2f\n", Accel.Accl_X_g, Accel.Accl_Y_g, Accel.Accl_Z_g);
		MPU_Angles(&Accel);
		printf("Pitch: %.2f, Roll: %.2f\n", Accel.pitch, Accel.roll);
		GPIO_Write_Toggle(GPIO_USER_LED, PIN_USER_LED);
		delay_ms(100);

	}
}

/* Definición de funciones */


/*
* Read MPU Acelerometer Values
*/
void MPU_Read_Accel(MPU6050_Accel_Data_t *Accel_t)
{
	uint8_t buffer[6];
	int16_t buff_X, buff_Y, buff_Z;

	I2C_Master_Read_Register_Bytes(I2C1, MPU6050_ADDR, 0x3B, Size_8bits, buffer, 6);
	buff_X = (int16_t)(buffer[0] << 8 | buffer[1]);
	buff_Y  = (int16_t)(buffer[2] << 8 | buffer[3]);
	buff_Z  = (int16_t)(buffer[4] << 8 | buffer[5]);

	Accel_t->Accel_X = buff_X - Accel_t->Accel_X_offset;
    Accel_t->Accel_Y = buff_Y - Accel_t->Accel_Y_offset;
    Accel_t->Accel_Z = buff_Z - Accel_t->Accel_Z_offset;

	Accel_t->Accel_X_g = Accel_t->Accel_X/16384.0f;
	Accel_t->Accel_Y_g = Accel_t->Accel_Y/16384.0f;
	Accel_t->Accel_Z_g = Accel_t->Accel_Z/16384.0f;

	return;
}

/*
 * @brief
 */
void MPU_Angles(MPU6050_Accel_Data_t *Accel_t)
{
	Accel_t->roll = atan2f(Accel_t->Accel_Y_g, Accel_t->Accel_Z_g) * RAD_TO_DEG;
	float hipotenusa = sqrtf(Accel_t->Accel_Y_g * Accel_t->Accel_Y_g + Accel_t->Accel_Z_g * Accel_t->Accel_Z_g);
	Accel_t->pitch = atan2f(-Accel_t->Accel_X_g, hipotenusa) * RAD_TO_DEG;

	return;
}

/*
* @brief Offset Calibration
*/
void MPU_Offset_Calibration(MPU6050_Accel_Data_t *Accel_t)
{
	uint8_t buff[6] = {0};
	int32_t sum_X = 0;
	int32_t sum_Y = 0;
	int32_t sum_Z = 0;
	int16_t raw_X, raw_Y, raw_Z;

	//Offset Calibration
	for(uint16_t i = 0; i < OFFSET_ITERATIONS; i++)
	{
		I2C_Master_Read_Register_Bytes(I2C1, MPU6050_ADDR, 0x3B, Size_8bits, buff, 6);
		
		raw_X = (int16_t)(buff[0] << 8 | buff[1]);
		raw_Y = (int16_t)(buff[2] << 8 | buff[3]);
		raw_Z = (int16_t)(buff[4] << 8 | buff[5]);

		sum_X += raw_X;
		sum_Y += raw_Y;
		sum_Z += raw_Z;

		delay_ms(10);
	}

	Accel_t->Accel_X_offset = (int16_t)(sum_X/OFFSET_ITERATIONS); //Por defecto en 0
	Accel_t->Accel_Y_offset = (int16_t)(sum_Y/OFFSET_ITERATIONS); //Por defecto en 0
	Accel_t->Accel_Z_offset = (int16_t)(sum_Z/OFFSET_ITERATIONS) - 16383; //Por defecto en 16383
	
	return;
}

/* 
* @brief Helpful function to write in console
*/
int __io_putchar(int ch)
{
	uint8_t c = ch & 0xFF;
	ITM_SendChar(c);
	return ch;
}

