/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/***************** Inclusión de librerías *****************/
#include <stdint.h>
#include <stdio.h>
#include "RCC.h"
#include "Delay.h"
#include "GPIO_Config.h"
#include "Timer2.h"
#include "Timer3.h"
#include "stm32f4xx.h"

/*Definiciones*/
#define LED_SYNC_GPIO	GPIOA
#define LED_SYNC_PIN	5
#define LED_PWM_GPIO	GPIOA
#define LED_PWN_PIN		7

/* Tipos, estructuras y enumeraciones */
PWM_tim3_t PWM3_Config = {
		.psc = 84-1,
		.arr = 100-1,
		.aligned_mode = Center_Aligned_3,
		.counting_mode = Upcounting,
		.polarity_mode = Active_High,
		.output_mode = PWM_Output_2,
		.isr = PWM_ISR_ON
};

/* Variables globales */
float DutyCycle = 0.0;
float Frequency = 0.0;
uint8_t duty = 50;

/* Prototipo de funciones */
void get_DC_Freq(void);
void tim3_handler(void);

/* Función principal */
int main(void)
{
	flash_config();
	PLL_Config(HSI_SOURCE);
	#if USE_DELAY_US == 1
		Delay_Init(SystemCoreClock/1000000); //Configurado a  84MHz
	#else
		Delay_Init(SystemCoreClock/1000);
	#endif

	/*PWM_Input_Capture*/
	//tim2_PWM_InputCapture_Config(ISR_ON);
	//tim2_PWM_InputCapture_Start();

	/*PWM Output Compare*/
	tim3_PWM_Config(&PWM3_Config);
	tim3_PWM_Start(80);

	//Configure Sync
	GPIO_Output_Config(LED_SYNC_GPIO, LED_SYNC_PIN, PUPDR_NONE, OSPEEDR_HIGH, OTYPER_PP);

	//Configure PWM Output
	//GPIO_Output_Config(LED_PWM_GPIO, LED_PWN_PIN, PUPDR_NONE, OSPEEDR_HIGH, OTYPER_PP);

	while(1)
	{

	}
}

/* Definición de funciones */

void get_DC_Freq(void)
{
	static uint8_t CC1IF_Counter = 0;
	static uint32_t Capture[2] = {0};

	if(TIM2->SR & TIM_SR_CC1IF)
	{
		CC1IF_Counter++;
		if(CC1IF_Counter == 2)
		{
			CC1IF_Counter = 0;
			Capture[1] = TIM2->CCR1;
			Frequency = 4000000.0f/Capture[1];
			DutyCycle = ((float)Capture[0]*100.0)/Capture[1];
		}
		TIM2->SR &= ~TIM_SR_CC1IF;
	}
	else if(TIM2->SR & TIM_SR_CC2IF)
	{
		Capture[0] = TIM2->CCR2;
		TIM2->SR &= ~TIM_SR_CC2IF;
	}
}

void tim3_handler(void)
{
	if(TIM3->SR & TIM_SR_CC2IF)
	{
		GPIO_Write_Toggle(LED_SYNC_GPIO, LED_SYNC_PIN);
		TIM3->SR &= ~TIM_SR_CC2IF;
	}
	return;
}



